import { getAirportCode } from "./cities";

export type FlightLeg = {
  from: string;
  to: string;
  departDate: string;
  flightNo?: string;
  departTime?: string;
  arrivalTime?: string;
  airlineName?: string;
  airlineCode?: string;
  price?: number;
};

export type Aircraft = {
  id: string;
  flightNo: string;
  airlineCode: string;
  airlineName: string;
  model: string;
  tailNumber: string;
  type: string;
  route: string;
  depTime: string;
  arrTime: string;
  capacity: number;
  businessSeats: number;
  economySeats: number;
  price?: number;
  priceStr?: string;
  originCity?: string;
  originCode?: string;
  destCity?: string;
  destCode?: string;
  terminalInfo?: string;
  durationStr?: string;
};

/**
 * Complete fleet of 117 aircraft corresponding to the active routes (green cells)
 * from "รายชื่อสนามบิน - ชีต1.pdf"
 */
export const MOCK_FLEET: Aircraft[] = [
  {
    "id": "BTN-001",
    "flightNo": "BTN201",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTBD",
    "type": "Narrow-body Jet",
    "route": "BKK → CNX",
    "depTime": "06:30",
    "arrTime": "07:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 960,
    "priceStr": "฿960",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "THA-002",
    "flightNo": "THA302",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THCG",
    "type": "Wide-body Jet",
    "route": "BKK → CEI",
    "depTime": "07:15",
    "arrTime": "08:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1430,
    "priceStr": "฿1,430",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "เชียงราย (CEI)",
    "destCode": "CEI",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BTN-003",
    "flightNo": "BTN203",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTDJ",
    "type": "Narrow-body Jet",
    "route": "BKK → HKT",
    "depTime": "08:00",
    "arrTime": "09:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1100,
    "priceStr": "฿1,100",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "ภูเก็ต (HKT)",
    "destCode": "HKT",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "THA-004",
    "flightNo": "THA304",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THEM",
    "type": "Wide-body Jet",
    "route": "BKK → HDY",
    "depTime": "08:45",
    "arrTime": "10:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1580,
    "priceStr": "฿1,580",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "สงขลา (HDY)",
    "destCode": "HDY",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BTN-005",
    "flightNo": "BTN205",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTFP",
    "type": "Narrow-body Jet",
    "route": "BKK → KBV",
    "depTime": "09:30",
    "arrTime": "10:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1250,
    "priceStr": "฿1,250",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "กระบี่ (KBV)",
    "destCode": "KBV",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "THA-006",
    "flightNo": "THA306",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THGS",
    "type": "Wide-body Jet",
    "route": "BKK → KKC",
    "depTime": "10:15",
    "arrTime": "11:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1720,
    "priceStr": "฿1,720",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "ขอนแก่น (KKC)",
    "destCode": "KKC",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BTN-007",
    "flightNo": "BTN207",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTHV",
    "type": "Narrow-body Jet",
    "route": "BKK → NST",
    "depTime": "11:00",
    "arrTime": "12:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1400,
    "priceStr": "฿1,400",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "นครศรีธรรมราช (NST)",
    "destCode": "NST",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "THA-008",
    "flightNo": "THA308",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THIY",
    "type": "Wide-body Jet",
    "route": "BKK → NAW",
    "depTime": "11:45",
    "arrTime": "13:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1870,
    "priceStr": "฿1,870",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "นราธิวาส (NAW)",
    "destCode": "NAW",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BTN-009",
    "flightNo": "BTN209",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTJB",
    "type": "Narrow-body Jet",
    "route": "BKK → BFV",
    "depTime": "12:30",
    "arrTime": "13:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1540,
    "priceStr": "฿1,540",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "บุรีรัมย์ (BFV)",
    "destCode": "BFV",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "THA-010",
    "flightNo": "THA310",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THKE",
    "type": "Wide-body Jet",
    "route": "BKK → LPT",
    "depTime": "13:15",
    "arrTime": "14:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2020,
    "priceStr": "฿2,020",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "ลำปาง (LPT)",
    "destCode": "LPT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BTN-011",
    "flightNo": "BTN211",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTLH",
    "type": "Narrow-body Jet",
    "route": "BKK → URT",
    "depTime": "14:00",
    "arrTime": "15:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1690,
    "priceStr": "฿1,690",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "สุราษฎร์ธานี (URT)",
    "destCode": "URT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "THA-012",
    "flightNo": "THA312",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THMK",
    "type": "Wide-body Jet",
    "route": "BKK → UTH",
    "depTime": "14:45",
    "arrTime": "16:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2160,
    "priceStr": "฿2,160",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "อุดรธานี (UTH)",
    "destCode": "UTH",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BTN-013",
    "flightNo": "BTN213",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTNN",
    "type": "Narrow-body Jet",
    "route": "BKK → UBP",
    "depTime": "15:30",
    "arrTime": "16:55",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1830,
    "priceStr": "฿1,830",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "อุบลราชธานี (UBP)",
    "destCode": "UBP",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BKP-014",
    "flightNo": "BKP414",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKOQ",
    "type": "Regional Turboprop",
    "route": "BKK → TDX",
    "depTime": "16:15",
    "arrTime": "17:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1910,
    "priceStr": "฿1,910",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "ตราด (TDX)",
    "destCode": "TDX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BTN-015",
    "flightNo": "BTN215",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTPT",
    "type": "Narrow-body Jet",
    "route": "BKK → USM",
    "depTime": "17:00",
    "arrTime": "18:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1980,
    "priceStr": "฿1,980",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "สุราษฎร์ธานี (USM)",
    "destCode": "USM",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BKP-016",
    "flightNo": "BKP416",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BKQW",
    "type": "Narrow-body Jet",
    "route": "BKK → THS",
    "depTime": "17:45",
    "arrTime": "19:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2050,
    "priceStr": "฿2,050",
    "originCity": "สมุทรปราการ (BKK)",
    "originCode": "BKK",
    "destCity": "สุโขทัย (THS)",
    "destCode": "THS",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารหลัก (สุวรรณภูมิ)"
  },
  {
    "id": "BTN-017",
    "flightNo": "BTN217",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTRZ",
    "type": "Narrow-body Jet",
    "route": "DMK → CNX",
    "depTime": "18:30",
    "arrTime": "19:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2130,
    "priceStr": "฿2,130",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "THA-018",
    "flightNo": "THA318",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THSC",
    "type": "Wide-body Jet",
    "route": "DMK → CEI",
    "depTime": "19:15",
    "arrTime": "20:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2200,
    "priceStr": "฿2,200",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "เชียงราย (CEI)",
    "destCode": "CEI",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-019",
    "flightNo": "BTN219",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTTF",
    "type": "Narrow-body Jet",
    "route": "DMK → HKT",
    "depTime": "20:00",
    "arrTime": "21:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 920,
    "priceStr": "฿920",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "ภูเก็ต (HKT)",
    "destCode": "HKT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-020",
    "flightNo": "BTN220",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTUI",
    "type": "Narrow-body Jet",
    "route": "DMK → HDY",
    "depTime": "20:45",
    "arrTime": "22:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1000,
    "priceStr": "฿1,000",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "สงขลา (HDY)",
    "destCode": "HDY",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "THA-021",
    "flightNo": "THA321",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-9 Dreamliner",
    "tailNumber": "HS-THVL",
    "type": "Wide-body Jet",
    "route": "DMK → KBV",
    "depTime": "06:00",
    "arrTime": "07:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1070,
    "priceStr": "฿1,070",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "กระบี่ (KBV)",
    "destCode": "KBV",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-022",
    "flightNo": "BTN222",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTWO",
    "type": "Narrow-body Jet",
    "route": "DMK → KKC",
    "depTime": "06:30",
    "arrTime": "07:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1140,
    "priceStr": "฿1,140",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "ขอนแก่น (KKC)",
    "destCode": "KKC",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-023",
    "flightNo": "BTN223",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTXR",
    "type": "Narrow-body Jet",
    "route": "DMK → CJM",
    "depTime": "07:15",
    "arrTime": "08:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1210,
    "priceStr": "฿1,210",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "ชุมพร (CJM)",
    "destCode": "CJM",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "THA-024",
    "flightNo": "THA324",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THYU",
    "type": "Wide-body Jet",
    "route": "DMK → TST",
    "depTime": "08:00",
    "arrTime": "09:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1290,
    "priceStr": "฿1,290",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "ตรัง (TST)",
    "destCode": "TST",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-025",
    "flightNo": "BTN225",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTZX",
    "type": "Narrow-body Jet",
    "route": "DMK → MAQ",
    "depTime": "08:45",
    "arrTime": "10:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1360,
    "priceStr": "฿1,360",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "ตาก (MAQ)",
    "destCode": "MAQ",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-026",
    "flightNo": "BTN226",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTAA",
    "type": "Narrow-body Jet",
    "route": "DMK → KOP",
    "depTime": "09:30",
    "arrTime": "10:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1430,
    "priceStr": "฿1,430",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "นครพนม (KOP)",
    "destCode": "KOP",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "THA-027",
    "flightNo": "THA327",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-8",
    "tailNumber": "HS-THBD",
    "type": "Wide-body Jet",
    "route": "DMK → NST",
    "depTime": "10:15",
    "arrTime": "11:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1510,
    "priceStr": "฿1,510",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "นครศรีธรรมราช (NST)",
    "destCode": "NST",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-028",
    "flightNo": "BTN228",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTCG",
    "type": "Narrow-body Jet",
    "route": "DMK → NAW",
    "depTime": "11:00",
    "arrTime": "12:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1580,
    "priceStr": "฿1,580",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "นราธิวาส (NAW)",
    "destCode": "NAW",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-029",
    "flightNo": "BTN229",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTDJ",
    "type": "Narrow-body Jet",
    "route": "DMK → NNT",
    "depTime": "11:45",
    "arrTime": "13:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1650,
    "priceStr": "฿1,650",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "น่าน (NNT)",
    "destCode": "NNT",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "THA-030",
    "flightNo": "THA330",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THEM",
    "type": "Wide-body Jet",
    "route": "DMK → BFV",
    "depTime": "12:30",
    "arrTime": "13:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1730,
    "priceStr": "฿1,730",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "บุรีรัมย์ (BFV)",
    "destCode": "BFV",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-031",
    "flightNo": "BTN231",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTFP",
    "type": "Narrow-body Jet",
    "route": "DMK → PHS",
    "depTime": "13:15",
    "arrTime": "14:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1800,
    "priceStr": "฿1,800",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "พิษณุโลก (PHS)",
    "destCode": "PHS",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-032",
    "flightNo": "BTN232",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTGS",
    "type": "Narrow-body Jet",
    "route": "DMK → ROI",
    "depTime": "14:00",
    "arrTime": "15:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1870,
    "priceStr": "฿1,870",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "ร้อยเอ็ด (ROI)",
    "destCode": "ROI",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "THA-033",
    "flightNo": "THA333",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-9 Dreamliner",
    "tailNumber": "HS-THHV",
    "type": "Wide-body Jet",
    "route": "DMK → UNN",
    "depTime": "14:45",
    "arrTime": "16:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1940,
    "priceStr": "฿1,940",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "ระนอง (UNN)",
    "destCode": "UNN",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-034",
    "flightNo": "BTN234",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTIY",
    "type": "Narrow-body Jet",
    "route": "DMK → LOE",
    "depTime": "15:30",
    "arrTime": "16:55",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2020,
    "priceStr": "฿2,020",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "เลย (LOE)",
    "destCode": "LOE",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-035",
    "flightNo": "BTN235",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTJB",
    "type": "Narrow-body Jet",
    "route": "DMK → LPT",
    "depTime": "16:15",
    "arrTime": "17:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2090,
    "priceStr": "฿2,090",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "ลำปาง (LPT)",
    "destCode": "LPT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "THA-036",
    "flightNo": "THA336",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THKE",
    "type": "Wide-body Jet",
    "route": "DMK → SNO",
    "depTime": "17:00",
    "arrTime": "18:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2160,
    "priceStr": "฿2,160",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "สกลนคร (SNO)",
    "destCode": "SNO",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-037",
    "flightNo": "BTN237",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTLH",
    "type": "Narrow-body Jet",
    "route": "DMK → URT",
    "depTime": "17:45",
    "arrTime": "19:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 890,
    "priceStr": "฿890",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "สุราษฎร์ธานี (URT)",
    "destCode": "URT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BTN-038",
    "flightNo": "BTN238",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTMK",
    "type": "Narrow-body Jet",
    "route": "DMK → UTH",
    "depTime": "18:30",
    "arrTime": "19:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 960,
    "priceStr": "฿960",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "อุดรธานี (UTH)",
    "destCode": "UTH",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "THA-039",
    "flightNo": "THA339",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-8",
    "tailNumber": "HS-THNN",
    "type": "Wide-body Jet",
    "route": "DMK → UBP",
    "depTime": "19:15",
    "arrTime": "20:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1030,
    "priceStr": "฿1,030",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "อุบลราชธานี (UBP)",
    "destCode": "UBP",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BKP-040",
    "flightNo": "BKP440",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BKOQ",
    "type": "Narrow-body Jet",
    "route": "DMK → USM",
    "depTime": "20:00",
    "arrTime": "21:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "กรุงเทพมหานคร (DMK)",
    "originCode": "DMK",
    "destCity": "สุราษฎร์ธานี (USM)",
    "destCode": "USM",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคาร 2 (ดอนเมือง)"
  },
  {
    "id": "BKP-041",
    "flightNo": "BKP441",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKPT",
    "type": "Regional Turboprop",
    "route": "CNX → BKK",
    "depTime": "20:45",
    "arrTime": "22:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1180,
    "priceStr": "฿1,180",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "BTN-042",
    "flightNo": "BTN242",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTQW",
    "type": "Narrow-body Jet",
    "route": "CNX → DMK",
    "depTime": "06:00",
    "arrTime": "07:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1250,
    "priceStr": "฿1,250",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "THA-043",
    "flightNo": "THA343",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-8",
    "tailNumber": "HS-THRZ",
    "type": "Wide-body Jet",
    "route": "CNX → HKT",
    "depTime": "06:30",
    "arrTime": "07:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1320,
    "priceStr": "฿1,320",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "ภูเก็ต (HKT)",
    "destCode": "HKT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "BKP-044",
    "flightNo": "BKP444",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKSC",
    "type": "Regional Turboprop",
    "route": "CNX → KBV",
    "depTime": "07:15",
    "arrTime": "08:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1400,
    "priceStr": "฿1,400",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "กระบี่ (KBV)",
    "destCode": "KBV",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "BTN-045",
    "flightNo": "BTN245",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTTF",
    "type": "Narrow-body Jet",
    "route": "CNX → KKC",
    "depTime": "08:00",
    "arrTime": "09:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1470,
    "priceStr": "฿1,470",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "ขอนแก่น (KKC)",
    "destCode": "KKC",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "THA-046",
    "flightNo": "THA346",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THUI",
    "type": "Wide-body Jet",
    "route": "CNX → HHQ",
    "depTime": "08:45",
    "arrTime": "10:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1540,
    "priceStr": "฿1,540",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "ประจวบคีรีขันธ์ (HHQ)",
    "destCode": "HHQ",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "BKP-047",
    "flightNo": "BKP447",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKVL",
    "type": "Regional Turboprop",
    "route": "CNX → URT",
    "depTime": "09:30",
    "arrTime": "10:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1620,
    "priceStr": "฿1,620",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "สุราษฎร์ธานี (URT)",
    "destCode": "URT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "BTN-048",
    "flightNo": "BTN248",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTWO",
    "type": "Narrow-body Jet",
    "route": "CNX → UTH",
    "depTime": "10:15",
    "arrTime": "11:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1690,
    "priceStr": "฿1,690",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "อุดรธานี (UTH)",
    "destCode": "UTH",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "THA-049",
    "flightNo": "THA349",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-9 Dreamliner",
    "tailNumber": "HS-THXR",
    "type": "Wide-body Jet",
    "route": "CNX → UTP",
    "depTime": "11:00",
    "arrTime": "12:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1760,
    "priceStr": "฿1,760",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "ระยอง (UTP)",
    "destCode": "UTP",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "BKP-050",
    "flightNo": "BKP450",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKYU",
    "type": "Regional Turboprop",
    "route": "CNX → USM",
    "depTime": "11:45",
    "arrTime": "13:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "เชียงใหม่ (CNX)",
    "originCode": "CNX",
    "destCity": "สุราษฎร์ธานี (USM)",
    "destCode": "USM",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงใหม่)"
  },
  {
    "id": "BTN-051",
    "flightNo": "BTN251",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTZX",
    "type": "Narrow-body Jet",
    "route": "CEI → BKK",
    "depTime": "12:30",
    "arrTime": "13:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1910,
    "priceStr": "฿1,910",
    "originCity": "เชียงราย (CEI)",
    "originCode": "CEI",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงราย)"
  },
  {
    "id": "THA-052",
    "flightNo": "THA352",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THAA",
    "type": "Wide-body Jet",
    "route": "CEI → DMK",
    "depTime": "13:15",
    "arrTime": "14:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1980,
    "priceStr": "฿1,980",
    "originCity": "เชียงราย (CEI)",
    "originCode": "CEI",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงราย)"
  },
  {
    "id": "BKP-053",
    "flightNo": "BKP453",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKBD",
    "type": "Regional Turboprop",
    "route": "CEI → HKT",
    "depTime": "14:00",
    "arrTime": "15:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2050,
    "priceStr": "฿2,050",
    "originCity": "เชียงราย (CEI)",
    "originCode": "CEI",
    "destCity": "ภูเก็ต (HKT)",
    "destCode": "HKT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เชียงราย)"
  },
  {
    "id": "BTN-054",
    "flightNo": "BTN254",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTCG",
    "type": "Narrow-body Jet",
    "route": "HKT → BKK",
    "depTime": "14:45",
    "arrTime": "16:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2130,
    "priceStr": "฿2,130",
    "originCity": "ภูเก็ต (HKT)",
    "originCode": "HKT",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ภูเก็ต)"
  },
  {
    "id": "THA-055",
    "flightNo": "THA355",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-8",
    "tailNumber": "HS-THDJ",
    "type": "Wide-body Jet",
    "route": "HKT → DMK",
    "depTime": "15:30",
    "arrTime": "16:55",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2200,
    "priceStr": "฿2,200",
    "originCity": "ภูเก็ต (HKT)",
    "originCode": "HKT",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ภูเก็ต)"
  },
  {
    "id": "BKP-056",
    "flightNo": "BKP456",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKEM",
    "type": "Regional Turboprop",
    "route": "HKT → CNX",
    "depTime": "16:15",
    "arrTime": "17:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 920,
    "priceStr": "฿920",
    "originCity": "ภูเก็ต (HKT)",
    "originCode": "HKT",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ภูเก็ต)"
  },
  {
    "id": "BTN-057",
    "flightNo": "BTN257",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTFP",
    "type": "Narrow-body Jet",
    "route": "HKT → CEI",
    "depTime": "17:00",
    "arrTime": "18:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1000,
    "priceStr": "฿1,000",
    "originCity": "ภูเก็ต (HKT)",
    "originCode": "HKT",
    "destCity": "เชียงราย (CEI)",
    "destCode": "CEI",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ภูเก็ต)"
  },
  {
    "id": "THA-058",
    "flightNo": "THA358",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THGS",
    "type": "Wide-body Jet",
    "route": "HKT → HDY",
    "depTime": "17:45",
    "arrTime": "19:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1070,
    "priceStr": "฿1,070",
    "originCity": "ภูเก็ต (HKT)",
    "originCode": "HKT",
    "destCity": "สงขลา (HDY)",
    "destCode": "HDY",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ภูเก็ต)"
  },
  {
    "id": "BKP-059",
    "flightNo": "BKP459",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKHV",
    "type": "Regional Turboprop",
    "route": "HKT → UTH",
    "depTime": "18:30",
    "arrTime": "19:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1140,
    "priceStr": "฿1,140",
    "originCity": "ภูเก็ต (HKT)",
    "originCode": "HKT",
    "destCity": "อุดรธานี (UTH)",
    "destCode": "UTH",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ภูเก็ต)"
  },
  {
    "id": "BTN-060",
    "flightNo": "BTN260",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTIY",
    "type": "Narrow-body Jet",
    "route": "HKT → UTP",
    "depTime": "19:15",
    "arrTime": "20:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1220,
    "priceStr": "฿1,220",
    "originCity": "ภูเก็ต (HKT)",
    "originCode": "HKT",
    "destCity": "ระยอง (UTP)",
    "destCode": "UTP",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ภูเก็ต)"
  },
  {
    "id": "BKP-061",
    "flightNo": "BKP461",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BKJB",
    "type": "Narrow-body Jet",
    "route": "HKT → USM",
    "depTime": "20:00",
    "arrTime": "21:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "ภูเก็ต (HKT)",
    "originCode": "HKT",
    "destCity": "สุราษฎร์ธานี (USM)",
    "destCode": "USM",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ภูเก็ต)"
  },
  {
    "id": "BKP-062",
    "flightNo": "BKP462",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKKE",
    "type": "Regional Turboprop",
    "route": "HDY → BKK",
    "depTime": "20:45",
    "arrTime": "22:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1360,
    "priceStr": "฿1,360",
    "originCity": "สงขลา (HDY)",
    "originCode": "HDY",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สงขลา (หาดใหญ่))"
  },
  {
    "id": "BTN-063",
    "flightNo": "BTN263",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTLH",
    "type": "Narrow-body Jet",
    "route": "HDY → DMK",
    "depTime": "06:00",
    "arrTime": "07:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1430,
    "priceStr": "฿1,430",
    "originCity": "สงขลา (HDY)",
    "originCode": "HDY",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สงขลา (หาดใหญ่))"
  },
  {
    "id": "THA-064",
    "flightNo": "THA364",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THMK",
    "type": "Wide-body Jet",
    "route": "HDY → CNX",
    "depTime": "06:30",
    "arrTime": "07:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1510,
    "priceStr": "฿1,510",
    "originCity": "สงขลา (HDY)",
    "originCode": "HDY",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สงขลา (หาดใหญ่))"
  },
  {
    "id": "BKP-065",
    "flightNo": "BKP465",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKNN",
    "type": "Regional Turboprop",
    "route": "HDY → HKT",
    "depTime": "07:15",
    "arrTime": "08:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1580,
    "priceStr": "฿1,580",
    "originCity": "สงขลา (HDY)",
    "originCode": "HDY",
    "destCity": "ภูเก็ต (HKT)",
    "destCode": "HKT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สงขลา (หาดใหญ่))"
  },
  {
    "id": "BTN-066",
    "flightNo": "BTN266",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTOQ",
    "type": "Narrow-body Jet",
    "route": "HDY → BTZ",
    "depTime": "08:00",
    "arrTime": "09:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1650,
    "priceStr": "฿1,650",
    "originCity": "สงขลา (HDY)",
    "originCode": "HDY",
    "destCity": "ยะลา (BTZ)",
    "destCode": "BTZ",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สงขลา (หาดใหญ่))"
  },
  {
    "id": "THA-067",
    "flightNo": "THA367",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-8",
    "tailNumber": "HS-THPT",
    "type": "Wide-body Jet",
    "route": "HDY → UTH",
    "depTime": "08:45",
    "arrTime": "10:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1730,
    "priceStr": "฿1,730",
    "originCity": "สงขลา (HDY)",
    "originCode": "HDY",
    "destCity": "อุดรธานี (UTH)",
    "destCode": "UTH",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สงขลา (หาดใหญ่))"
  },
  {
    "id": "BKP-068",
    "flightNo": "BKP468",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKQW",
    "type": "Regional Turboprop",
    "route": "KBV → BKK",
    "depTime": "09:30",
    "arrTime": "10:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1800,
    "priceStr": "฿1,800",
    "originCity": "กระบี่ (KBV)",
    "originCode": "KBV",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (กระบี่)"
  },
  {
    "id": "BTN-069",
    "flightNo": "BTN269",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTRZ",
    "type": "Narrow-body Jet",
    "route": "KBV → DMK",
    "depTime": "10:15",
    "arrTime": "11:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1870,
    "priceStr": "฿1,870",
    "originCity": "กระบี่ (KBV)",
    "originCode": "KBV",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (กระบี่)"
  },
  {
    "id": "THA-070",
    "flightNo": "THA370",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THSC",
    "type": "Wide-body Jet",
    "route": "KBV → CNX",
    "depTime": "11:00",
    "arrTime": "12:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "กระบี่ (KBV)",
    "originCode": "KBV",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (กระบี่)"
  },
  {
    "id": "BKP-071",
    "flightNo": "BKP471",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKTF",
    "type": "Regional Turboprop",
    "route": "KBV → USM",
    "depTime": "11:45",
    "arrTime": "13:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2020,
    "priceStr": "฿2,020",
    "originCity": "กระบี่ (KBV)",
    "originCode": "KBV",
    "destCity": "สุราษฎร์ธานี (USM)",
    "destCode": "USM",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (กระบี่)"
  },
  {
    "id": "BTN-072",
    "flightNo": "BTN272",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTUI",
    "type": "Narrow-body Jet",
    "route": "KKC → BKK",
    "depTime": "12:30",
    "arrTime": "13:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2090,
    "priceStr": "฿2,090",
    "originCity": "ขอนแก่น (KKC)",
    "originCode": "KKC",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ขอนแก่น)"
  },
  {
    "id": "THA-073",
    "flightNo": "THA373",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-9 Dreamliner",
    "tailNumber": "HS-THVL",
    "type": "Wide-body Jet",
    "route": "KKC → DMK",
    "depTime": "13:15",
    "arrTime": "14:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2160,
    "priceStr": "฿2,160",
    "originCity": "ขอนแก่น (KKC)",
    "originCode": "KKC",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ขอนแก่น)"
  },
  {
    "id": "BKP-074",
    "flightNo": "BKP474",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKWO",
    "type": "Regional Turboprop",
    "route": "KKC → CNX",
    "depTime": "14:00",
    "arrTime": "15:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 890,
    "priceStr": "฿890",
    "originCity": "ขอนแก่น (KKC)",
    "originCode": "KKC",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ขอนแก่น)"
  },
  {
    "id": "BTN-075",
    "flightNo": "BTN275",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTXR",
    "type": "Narrow-body Jet",
    "route": "CJM → DMK",
    "depTime": "14:45",
    "arrTime": "16:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 960,
    "priceStr": "฿960",
    "originCity": "ชุมพร (CJM)",
    "originCode": "CJM",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ชุมพร)"
  },
  {
    "id": "THA-076",
    "flightNo": "THA376",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THYU",
    "type": "Wide-body Jet",
    "route": "TST → DMK",
    "depTime": "15:30",
    "arrTime": "16:55",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1030,
    "priceStr": "฿1,030",
    "originCity": "ตรัง (TST)",
    "originCode": "TST",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ตรัง)"
  },
  {
    "id": "BKP-077",
    "flightNo": "BKP477",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKZX",
    "type": "Regional Turboprop",
    "route": "MAQ → DMK",
    "depTime": "16:15",
    "arrTime": "17:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1110,
    "priceStr": "฿1,110",
    "originCity": "ตาก (MAQ)",
    "originCode": "MAQ",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ตาก (แม่สอด))"
  },
  {
    "id": "BTN-078",
    "flightNo": "BTN278",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTAA",
    "type": "Narrow-body Jet",
    "route": "KOP → DMK",
    "depTime": "17:00",
    "arrTime": "18:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1180,
    "priceStr": "฿1,180",
    "originCity": "นครพนม (KOP)",
    "originCode": "KOP",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (นครพนม)"
  },
  {
    "id": "THA-079",
    "flightNo": "THA379",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-8",
    "tailNumber": "HS-THBD",
    "type": "Wide-body Jet",
    "route": "NST → BKK",
    "depTime": "17:45",
    "arrTime": "19:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1250,
    "priceStr": "฿1,250",
    "originCity": "นครศรีธรรมราช (NST)",
    "originCode": "NST",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (นครศรีธรรมราช)"
  },
  {
    "id": "BKP-080",
    "flightNo": "BKP480",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKCG",
    "type": "Regional Turboprop",
    "route": "NST → DMK",
    "depTime": "18:30",
    "arrTime": "19:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1330,
    "priceStr": "฿1,330",
    "originCity": "นครศรีธรรมราช (NST)",
    "originCode": "NST",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (นครศรีธรรมราช)"
  },
  {
    "id": "BTN-081",
    "flightNo": "BTN281",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTDJ",
    "type": "Narrow-body Jet",
    "route": "NAW → BKK",
    "depTime": "19:15",
    "arrTime": "20:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1400,
    "priceStr": "฿1,400",
    "originCity": "นราธิวาส (NAW)",
    "originCode": "NAW",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (นราธิวาส)"
  },
  {
    "id": "THA-082",
    "flightNo": "THA382",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THEM",
    "type": "Wide-body Jet",
    "route": "NAW → DMK",
    "depTime": "20:00",
    "arrTime": "21:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1470,
    "priceStr": "฿1,470",
    "originCity": "นราธิวาส (NAW)",
    "originCode": "NAW",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (นราธิวาส)"
  },
  {
    "id": "BKP-083",
    "flightNo": "BKP483",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKFP",
    "type": "Regional Turboprop",
    "route": "NNT → DMK",
    "depTime": "20:45",
    "arrTime": "22:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1540,
    "priceStr": "฿1,540",
    "originCity": "น่าน (NNT)",
    "originCode": "NNT",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (น่าน (น่านนคร))"
  },
  {
    "id": "BTN-084",
    "flightNo": "BTN284",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTGS",
    "type": "Narrow-body Jet",
    "route": "BFV → BKK",
    "depTime": "06:00",
    "arrTime": "07:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1620,
    "priceStr": "฿1,620",
    "originCity": "บุรีรัมย์ (BFV)",
    "originCode": "BFV",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (บุรีรัมย์)"
  },
  {
    "id": "THA-085",
    "flightNo": "THA385",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-9 Dreamliner",
    "tailNumber": "HS-THHV",
    "type": "Wide-body Jet",
    "route": "BFV → DMK",
    "depTime": "06:30",
    "arrTime": "07:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1690,
    "priceStr": "฿1,690",
    "originCity": "บุรีรัมย์ (BFV)",
    "originCode": "BFV",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (บุรีรัมย์)"
  },
  {
    "id": "BKP-086",
    "flightNo": "BKP486",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKIY",
    "type": "Regional Turboprop",
    "route": "HHQ → CNX",
    "depTime": "07:15",
    "arrTime": "08:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1760,
    "priceStr": "฿1,760",
    "originCity": "ประจวบคีรีขันธ์ (HHQ)",
    "originCode": "HHQ",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ประจวบคีรีขันธ์ (หัวหิน))"
  },
  {
    "id": "BTN-087",
    "flightNo": "BTN287",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTJB",
    "type": "Narrow-body Jet",
    "route": "PHS → DMK",
    "depTime": "08:00",
    "arrTime": "09:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1840,
    "priceStr": "฿1,840",
    "originCity": "พิษณุโลก (PHS)",
    "originCode": "PHS",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (พิษณุโลก)"
  },
  {
    "id": "THA-088",
    "flightNo": "THA388",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THKE",
    "type": "Wide-body Jet",
    "route": "BTZ → HDY",
    "depTime": "08:45",
    "arrTime": "10:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1910,
    "priceStr": "฿1,910",
    "originCity": "ยะลา (BTZ)",
    "originCode": "BTZ",
    "destCity": "สงขลา (HDY)",
    "destCode": "HDY",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ยะลา (เบตง))"
  },
  {
    "id": "BKP-089",
    "flightNo": "BKP489",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKLH",
    "type": "Regional Turboprop",
    "route": "ROI → DMK",
    "depTime": "09:30",
    "arrTime": "10:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1980,
    "priceStr": "฿1,980",
    "originCity": "ร้อยเอ็ด (ROI)",
    "originCode": "ROI",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ร้อยเอ็ด)"
  },
  {
    "id": "BTN-090",
    "flightNo": "BTN290",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTMK",
    "type": "Narrow-body Jet",
    "route": "UNN → DMK",
    "depTime": "10:15",
    "arrTime": "11:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2060,
    "priceStr": "฿2,060",
    "originCity": "ระนอง (UNN)",
    "originCode": "UNN",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ระนอง)"
  },
  {
    "id": "THA-091",
    "flightNo": "THA391",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-8",
    "tailNumber": "HS-THNN",
    "type": "Wide-body Jet",
    "route": "LOE → DMK",
    "depTime": "11:00",
    "arrTime": "12:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2130,
    "priceStr": "฿2,130",
    "originCity": "เลย (LOE)",
    "originCode": "LOE",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (เลย)"
  },
  {
    "id": "BKP-092",
    "flightNo": "BKP492",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKOQ",
    "type": "Regional Turboprop",
    "route": "LPT → BKK",
    "depTime": "11:45",
    "arrTime": "13:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2200,
    "priceStr": "฿2,200",
    "originCity": "ลำปาง (LPT)",
    "originCode": "LPT",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ลำปาง)"
  },
  {
    "id": "BTN-093",
    "flightNo": "BTN293",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTPT",
    "type": "Narrow-body Jet",
    "route": "LPT → DMK",
    "depTime": "12:30",
    "arrTime": "13:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 920,
    "priceStr": "฿920",
    "originCity": "ลำปาง (LPT)",
    "originCode": "LPT",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ลำปาง)"
  },
  {
    "id": "THA-094",
    "flightNo": "THA394",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Airbus A350-900",
    "tailNumber": "HS-THQW",
    "type": "Wide-body Jet",
    "route": "SNO → DMK",
    "depTime": "13:15",
    "arrTime": "14:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1000,
    "priceStr": "฿1,000",
    "originCity": "สกลนคร (SNO)",
    "originCode": "SNO",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สกลนคร)"
  },
  {
    "id": "BKP-095",
    "flightNo": "BKP495",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKRZ",
    "type": "Regional Turboprop",
    "route": "URT → BKK",
    "depTime": "14:00",
    "arrTime": "15:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1070,
    "priceStr": "฿1,070",
    "originCity": "สุราษฎร์ธานี (URT)",
    "originCode": "URT",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี)"
  },
  {
    "id": "BTN-096",
    "flightNo": "BTN296",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTSC",
    "type": "Narrow-body Jet",
    "route": "URT → DMK",
    "depTime": "14:45",
    "arrTime": "16:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1140,
    "priceStr": "฿1,140",
    "originCity": "สุราษฎร์ธานี (URT)",
    "originCode": "URT",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี)"
  },
  {
    "id": "THA-097",
    "flightNo": "THA397",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-9 Dreamliner",
    "tailNumber": "HS-THTF",
    "type": "Wide-body Jet",
    "route": "URT → CNX",
    "depTime": "15:30",
    "arrTime": "16:55",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1220,
    "priceStr": "฿1,220",
    "originCity": "สุราษฎร์ธานี (URT)",
    "originCode": "URT",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี)"
  },
  {
    "id": "BKP-098",
    "flightNo": "BKP498",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKUI",
    "type": "Regional Turboprop",
    "route": "UTH → BKK",
    "depTime": "16:15",
    "arrTime": "17:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1290,
    "priceStr": "฿1,290",
    "originCity": "อุดรธานี (UTH)",
    "originCode": "UTH",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (อุดรธานี)"
  },
  {
    "id": "BTN-099",
    "flightNo": "BTN299",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTVL",
    "type": "Narrow-body Jet",
    "route": "UTH → DMK",
    "depTime": "17:00",
    "arrTime": "18:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1360,
    "priceStr": "฿1,360",
    "originCity": "อุดรธานี (UTH)",
    "originCode": "UTH",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (อุดรธานี)"
  },
  {
    "id": "THA-100",
    "flightNo": "THA400",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 777-300ER",
    "tailNumber": "HS-THWO",
    "type": "Wide-body Jet",
    "route": "UTH → CNX",
    "depTime": "17:45",
    "arrTime": "19:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1440,
    "priceStr": "฿1,440",
    "originCity": "อุดรธานี (UTH)",
    "originCode": "UTH",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (อุดรธานี)"
  },
  {
    "id": "BKP-101",
    "flightNo": "BKP501",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKXR",
    "type": "Regional Turboprop",
    "route": "UTH → HKT",
    "depTime": "18:30",
    "arrTime": "19:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1510,
    "priceStr": "฿1,510",
    "originCity": "อุดรธานี (UTH)",
    "originCode": "UTH",
    "destCity": "ภูเก็ต (HKT)",
    "destCode": "HKT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (อุดรธานี)"
  },
  {
    "id": "BTN-102",
    "flightNo": "BTN302",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTYU",
    "type": "Narrow-body Jet",
    "route": "UTH → HDY",
    "depTime": "19:15",
    "arrTime": "20:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1580,
    "priceStr": "฿1,580",
    "originCity": "อุดรธานี (UTH)",
    "originCode": "UTH",
    "destCity": "สงขลา (HDY)",
    "destCode": "HDY",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (อุดรธานี)"
  },
  {
    "id": "THA-103",
    "flightNo": "THA403",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-8",
    "tailNumber": "HS-THZX",
    "type": "Wide-body Jet",
    "route": "UTH → UTP",
    "depTime": "20:00",
    "arrTime": "21:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1650,
    "priceStr": "฿1,650",
    "originCity": "อุดรธานี (UTH)",
    "originCode": "UTH",
    "destCity": "ระยอง (UTP)",
    "destCode": "UTP",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (อุดรธานี)"
  },
  {
    "id": "BKP-104",
    "flightNo": "BKP504",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKAA",
    "type": "Regional Turboprop",
    "route": "UBP → BKK",
    "depTime": "20:45",
    "arrTime": "22:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1730,
    "priceStr": "฿1,730",
    "originCity": "อุบลราชธานี (UBP)",
    "originCode": "UBP",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (อุบลราชธานี)"
  },
  {
    "id": "BTN-105",
    "flightNo": "BTN305",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTBD",
    "type": "Narrow-body Jet",
    "route": "UBP → DMK",
    "depTime": "06:00",
    "arrTime": "07:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1800,
    "priceStr": "฿1,800",
    "originCity": "อุบลราชธานี (UBP)",
    "originCode": "UBP",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (อุบลราชธานี)"
  },
  {
    "id": "BKP-106",
    "flightNo": "BKP506",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BKCG",
    "type": "Narrow-body Jet",
    "route": "TDX → BKK",
    "depTime": "06:30",
    "arrTime": "07:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1870,
    "priceStr": "฿1,870",
    "originCity": "ตราด (TDX)",
    "originCode": "TDX",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ตราด)"
  },
  {
    "id": "BKP-107",
    "flightNo": "BKP507",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKDJ",
    "type": "Regional Turboprop",
    "route": "UTP → CNX",
    "depTime": "07:15",
    "arrTime": "08:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "ระยอง (UTP)",
    "originCode": "UTP",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ระยอง (อู่ตะเภา))"
  },
  {
    "id": "BTN-108",
    "flightNo": "BTN308",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BTEM",
    "type": "Narrow-body Jet",
    "route": "UTP → HKT",
    "depTime": "08:00",
    "arrTime": "09:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2020,
    "priceStr": "฿2,020",
    "originCity": "ระยอง (UTP)",
    "originCode": "UTP",
    "destCity": "ภูเก็ต (HKT)",
    "destCode": "HKT",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ระยอง (อู่ตะเภา))"
  },
  {
    "id": "THA-109",
    "flightNo": "THA409",
    "airlineCode": "THA",
    "airlineName": "Thai Airways",
    "model": "Boeing 787-9 Dreamliner",
    "tailNumber": "HS-THFP",
    "type": "Wide-body Jet",
    "route": "UTP → UTH",
    "depTime": "08:45",
    "arrTime": "10:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2090,
    "priceStr": "฿2,090",
    "originCity": "ระยอง (UTP)",
    "originCode": "UTP",
    "destCity": "อุดรธานี (UTH)",
    "destCode": "UTH",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ระยอง (อู่ตะเภา))"
  },
  {
    "id": "BKP-110",
    "flightNo": "BKP510",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKGS",
    "type": "Regional Turboprop",
    "route": "UTP → USM",
    "depTime": "09:30",
    "arrTime": "10:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 2170,
    "priceStr": "฿2,170",
    "originCity": "ระยอง (UTP)",
    "originCode": "UTP",
    "destCity": "สุราษฎร์ธานี (USM)",
    "destCode": "USM",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (ระยอง (อู่ตะเภา))"
  },
  {
    "id": "BTN-111",
    "flightNo": "BTN311",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A320neo",
    "tailNumber": "HS-BTHV",
    "type": "Narrow-body Jet",
    "route": "USM → BKK",
    "depTime": "10:15",
    "arrTime": "11:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "สุราษฎร์ธานี (USM)",
    "originCode": "USM",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี (สมุย))"
  },
  {
    "id": "BKP-112",
    "flightNo": "BKP512",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BKIY",
    "type": "Narrow-body Jet",
    "route": "USM → DMK",
    "depTime": "11:00",
    "arrTime": "12:15",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "สุราษฎร์ธานี (USM)",
    "originCode": "USM",
    "destCity": "กรุงเทพมหานคร (DMK)",
    "destCode": "DMK",
    "durationStr": "1 ชม. 15 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี (สมุย))"
  },
  {
    "id": "BKP-113",
    "flightNo": "BKP513",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKJB",
    "type": "Regional Turboprop",
    "route": "USM → CNX",
    "depTime": "11:45",
    "arrTime": "13:10",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "สุราษฎร์ธานี (USM)",
    "originCode": "USM",
    "destCity": "เชียงใหม่ (CNX)",
    "destCode": "CNX",
    "durationStr": "1 ชม. 25 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี (สมุย))"
  },
  {
    "id": "BTN-114",
    "flightNo": "BTN314",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Boeing 737-800",
    "tailNumber": "HS-BTKE",
    "type": "Narrow-body Jet",
    "route": "USM → HKT",
    "depTime": "12:30",
    "arrTime": "13:50",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "สุราษฎร์ธานี (USM)",
    "originCode": "USM",
    "destCity": "ภูเก็ต (HKT)",
    "destCode": "HKT",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี (สมุย))"
  },
  {
    "id": "BKP-115",
    "flightNo": "BKP515",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "Airbus A320-200",
    "tailNumber": "HS-BKLH",
    "type": "Narrow-body Jet",
    "route": "USM → KBV",
    "depTime": "13:15",
    "arrTime": "14:35",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "สุราษฎร์ธานี (USM)",
    "originCode": "USM",
    "destCity": "กระบี่ (KBV)",
    "destCode": "KBV",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี (สมุย))"
  },
  {
    "id": "BKP-116",
    "flightNo": "BKP516",
    "airlineCode": "BKP",
    "airlineName": "Bangkok Airways",
    "model": "ATR 72-600",
    "tailNumber": "HS-BKMK",
    "type": "Regional Turboprop",
    "route": "USM → UTP",
    "depTime": "14:00",
    "arrTime": "15:20",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1950,
    "priceStr": "฿1,950",
    "originCity": "สุราษฎร์ธานี (USM)",
    "originCode": "USM",
    "destCity": "ระยอง (UTP)",
    "destCode": "UTP",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุราษฎร์ธานี (สมุย))"
  },
  {
    "id": "BTN-117",
    "flightNo": "BTN317",
    "airlineCode": "BTN",
    "airlineName": "Botnoi Air",
    "model": "Airbus A321neo",
    "tailNumber": "HS-BTNN",
    "type": "Narrow-body Jet",
    "route": "THS → BKK",
    "depTime": "14:45",
    "arrTime": "16:05",
    "capacity": 60,
    "businessSeats": 12,
    "economySeats": 48,
    "price": 1330,
    "priceStr": "฿1,330",
    "originCity": "สุโขทัย (THS)",
    "originCode": "THS",
    "destCity": "สมุทรปราการ (BKK)",
    "destCode": "BKK",
    "durationStr": "1 ชม. 20 นาที",
    "terminalInfo": "อาคารผู้โดยสารภายในประเทศ (สุโขทัย)"
  }
];

export type Booking = {
  id: string;
  createdAt: string;
  tripType: "round" | "oneway" | "multicity";
  from: string;
  to: string;
  departDate: string;
  returnDate?: string;
  legs?: FlightLeg[];
  passengers: number;
  promoCode?: string;
  passengerName: string;
  email: string;
  phone: string;
  seat?: string;
  pricePerPax?: number;
  class?: string;
  aircraftModel?: string;
  aircraftTail?: string;
  outboundFlightNo?: string;
  outboundTime?: string;
  inboundFlightNo?: string;
  inboundTime?: string;
};

const KEY = "nok_bookings";

export function getBookings(): Booking[] {
  if (typeof window === "undefined") return [];
  try {
    return JSON.parse(localStorage.getItem(KEY) || "[]");
  } catch {
    return [];
  }
}

export function saveBooking(b: Omit<Booking, "id" | "createdAt">): Booking {
  const booking: Booking = {
    ...b,
    id: crypto.randomUUID(),
    createdAt: new Date().toISOString(),
  };
  const all = getBookings();
  all.unshift(booking);
  localStorage.setItem(KEY, JSON.stringify(all));
  return booking;
}

export function deleteBooking(id: string) {
  const all = getBookings().filter((b) => b.id !== id);
  localStorage.setItem(KEY, JSON.stringify(all));
}

export function clearBookings() {
  localStorage.removeItem(KEY);
}

export const DEFAULT_FLIGHT_LOCKED_SEATS: Record<string, string[]> = {
  "BTN201": [
    "2F",
    "3D",
    "4F",
    "5D",
    "8C",
    "9B"
  ],
  "THA302": [
    "4D",
    "6G",
    "7A",
    "8B",
    "8G"
  ],
  "BTN203": [
    "1F",
    "2A",
    "3D",
    "6C",
    "8D",
    "9C"
  ],
  "THA304": [
    "3K",
    "4K",
    "7G",
    "7K",
    "8G"
  ],
  "BTN205": [
    "3A",
    "4D",
    "6C",
    "6E",
    "9B"
  ],
  "THA306": [
    "3A",
    "3B",
    "6A",
    "7G",
    "7J",
    "8B",
    "8K"
  ],
  "BTN207": [
    "1B",
    "2A",
    "3A",
    "3B",
    "4A",
    "6A",
    "7A",
    "7F"
  ],
  "THA308": [
    "2F",
    "3D",
    "4D",
    "5A",
    "5E",
    "5J",
    "6B",
    "7D"
  ],
  "BTN209": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ],
  "THA310": [
    "1A",
    "1F",
    "3K",
    "4E",
    "6K",
    "7G",
    "8B"
  ],
  "BTN211": [
    "2A",
    "2E",
    "4A",
    "5A",
    "5D",
    "6A",
    "6D",
    "8A"
  ],
  "THA312": [
    "2F",
    "3K",
    "4F",
    "5D",
    "6J",
    "6K",
    "8J"
  ],
  "BTN213": [
    "4A",
    "5B",
    "5F",
    "8C",
    "8D"
  ],
  "BKP414": [
    "3A",
    "3C",
    "9A",
    "12C",
    "13C",
    "14C",
    "15F"
  ],
  "BTN215": [
    "4D",
    "5C",
    "6F",
    "7A",
    "9C",
    "9F"
  ],
  "BKP416": [
    "2A",
    "2E",
    "4A",
    "5A",
    "5D",
    "6A",
    "6D",
    "8A"
  ],
  "BTN217": [
    "2C",
    "3C",
    "3E",
    "4D",
    "6C"
  ],
  "THA318": [
    "2E",
    "2F",
    "3K",
    "6A",
    "7G",
    "8D"
  ],
  "BTN219": [
    "1B",
    "1D",
    "4F",
    "6E",
    "7E",
    "8F",
    "9B",
    "9C"
  ],
  "BTN220": [
    "2A",
    "2E",
    "4A",
    "5A",
    "5D",
    "6A",
    "6D",
    "8A"
  ],
  "THA321": [
    "2F",
    "3K",
    "4F",
    "5D",
    "6J",
    "6K",
    "8J"
  ],
  "BTN222": [
    "4A",
    "5B",
    "5F",
    "8C",
    "8D"
  ],
  "BTN223": [
    "3A",
    "4D",
    "6C",
    "6E",
    "9B"
  ],
  "THA324": [
    "3A",
    "3B",
    "6A",
    "7G",
    "7J",
    "8B",
    "8K"
  ],
  "BTN225": [
    "1B",
    "2A",
    "3A",
    "3B",
    "4A",
    "6A",
    "7A",
    "7F"
  ],
  "BTN226": [
    "2C",
    "3C",
    "3E",
    "4D",
    "6C"
  ],
  "THA327": [
    "2E",
    "2F",
    "3K",
    "6A",
    "7G",
    "8D"
  ],
  "BTN228": [
    "1B",
    "1D",
    "4F",
    "6E",
    "7E",
    "8F",
    "9B",
    "9C"
  ],
  "BTN229": [
    "4B",
    "5B",
    "6B",
    "6D",
    "9E"
  ],
  "THA330": [
    "2F",
    "3K",
    "4F",
    "5D",
    "6J",
    "6K",
    "8J"
  ],
  "BTN231": [
    "4A",
    "5B",
    "5F",
    "8C",
    "8D"
  ],
  "BTN232": [
    "3A",
    "4D",
    "6C",
    "6E",
    "9B"
  ],
  "THA333": [
    "3A",
    "3B",
    "6A",
    "7G",
    "7J",
    "8B",
    "8K"
  ],
  "BTN234": [
    "1B",
    "2A",
    "3A",
    "3B",
    "4A",
    "6A",
    "7A",
    "7F"
  ],
  "BTN235": [
    "2C",
    "3C",
    "3E",
    "4D",
    "6C"
  ],
  "THA336": [
    "2E",
    "2F",
    "3K",
    "6A",
    "7G",
    "8D"
  ],
  "BTN237": [
    "1B",
    "1D",
    "4F",
    "6E",
    "7E",
    "8F",
    "9B",
    "9C"
  ],
  "BTN238": [
    "4B",
    "5B",
    "6B",
    "6D",
    "9E"
  ],
  "THA339": [
    "4G",
    "5D",
    "5F",
    "6E",
    "6F",
    "8D"
  ],
  "BKP440": [
    "2B",
    "8A",
    "8F",
    "9C",
    "10C"
  ],
  "BKP441": [
    "3A",
    "3C",
    "9A",
    "12C",
    "13C",
    "14C",
    "15F"
  ],
  "BTN242": [
    "4D",
    "5C",
    "6F",
    "7A",
    "9C",
    "9F"
  ],
  "THA343": [
    "3E",
    "3K",
    "4K",
    "5E",
    "7F",
    "8B"
  ],
  "BKP444": [
    "2C",
    "2D",
    "4F",
    "9A",
    "12C",
    "13D"
  ],
  "BTN245": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ],
  "THA346": [
    "4D",
    "5B",
    "5G",
    "7F",
    "7G"
  ],
  "BKP447": [
    "6C",
    "7D",
    "9F",
    "10A",
    "13D",
    "14C"
  ],
  "BTN248": [
    "1D",
    "5B",
    "5C",
    "5E",
    "6D",
    "6E",
    "8C"
  ],
  "THA349": [
    "1E",
    "2F",
    "3F",
    "3G",
    "4D",
    "5J",
    "6F",
    "7B"
  ],
  "BKP450": [
    "3A",
    "3C",
    "9A",
    "12C",
    "13C",
    "14C",
    "15F"
  ],
  "BTN251": [
    "4D",
    "5C",
    "6F",
    "7A",
    "9C",
    "9F"
  ],
  "THA352": [
    "3E",
    "3K",
    "4K",
    "5E",
    "7F",
    "8B"
  ],
  "BKP453": [
    "2C",
    "2D",
    "4F",
    "9A",
    "12C",
    "13D"
  ],
  "BTN254": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ],
  "THA355": [
    "4D",
    "5B",
    "5G",
    "7F",
    "7G"
  ],
  "BKP456": [
    "6C",
    "7D",
    "9F",
    "10A",
    "13D",
    "14C"
  ],
  "BTN257": [
    "1D",
    "5B",
    "5C",
    "5E",
    "6D",
    "6E",
    "8C"
  ],
  "THA358": [
    "1E",
    "2F",
    "3F",
    "3G",
    "4D",
    "5J",
    "6F",
    "7B"
  ],
  "BKP459": [
    "2D",
    "3C",
    "4D",
    "5F",
    "6F",
    "8D",
    "11C",
    "13D"
  ],
  "BTN260": [
    "4D",
    "5C",
    "6F",
    "7A",
    "9C",
    "9F"
  ],
  "BKP461": [
    "2A",
    "2E",
    "4A",
    "5A",
    "5D",
    "6A",
    "6D",
    "8A"
  ],
  "BKP462": [
    "2C",
    "2D",
    "4F",
    "9A",
    "12C",
    "13D"
  ],
  "BTN263": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ],
  "THA364": [
    "4D",
    "5B",
    "5G",
    "7F",
    "7G"
  ],
  "BKP465": [
    "6C",
    "7D",
    "9F",
    "10A",
    "13D",
    "14C"
  ],
  "BTN266": [
    "1D",
    "5B",
    "5C",
    "5E",
    "6D",
    "6E",
    "8C"
  ],
  "THA367": [
    "1E",
    "2F",
    "3F",
    "3G",
    "4D",
    "5J",
    "6F",
    "7B"
  ],
  "BKP468": [
    "2D",
    "3C",
    "4D",
    "5F",
    "6F",
    "8D",
    "11C",
    "13D"
  ],
  "BTN269": [
    "3C",
    "3D",
    "5C",
    "6A",
    "6E",
    "7A",
    "9C"
  ],
  "THA370": [
    "3E",
    "3K",
    "4K",
    "5E",
    "7F",
    "8B"
  ],
  "BKP471": [
    "2C",
    "2D",
    "4F",
    "9A",
    "12C",
    "13D"
  ],
  "BTN272": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ],
  "THA373": [
    "4D",
    "5B",
    "5G",
    "7F",
    "7G"
  ],
  "BKP474": [
    "6C",
    "7D",
    "9F",
    "10A",
    "13D",
    "14C"
  ],
  "BTN275": [
    "1D",
    "5B",
    "5C",
    "5E",
    "6D",
    "6E",
    "8C"
  ],
  "THA376": [
    "1E",
    "2F",
    "3F",
    "3G",
    "4D",
    "5J",
    "6F",
    "7B"
  ],
  "BKP477": [
    "2D",
    "3C",
    "4D",
    "5F",
    "6F",
    "8D",
    "11C",
    "13D"
  ],
  "BTN278": [
    "3C",
    "3D",
    "5C",
    "6A",
    "6E",
    "7A",
    "9C"
  ],
  "THA379": [
    "1E",
    "1K",
    "4K",
    "6D",
    "7A",
    "7K",
    "8B",
    "8D"
  ],
  "BKP480": [
    "2C",
    "2D",
    "4F",
    "9A",
    "12C",
    "13D"
  ],
  "BTN281": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ],
  "THA382": [
    "4D",
    "5B",
    "5G",
    "7F",
    "7G"
  ],
  "BKP483": [
    "6C",
    "7D",
    "9F",
    "10A",
    "13D",
    "14C"
  ],
  "BTN284": [
    "1D",
    "5B",
    "5C",
    "5E",
    "6D",
    "6E",
    "8C"
  ],
  "THA385": [
    "1E",
    "2F",
    "3F",
    "3G",
    "4D",
    "5J",
    "6F",
    "7B"
  ],
  "BKP486": [
    "2D",
    "3C",
    "4D",
    "5F",
    "6F",
    "8D",
    "11C",
    "13D"
  ],
  "BTN287": [
    "3C",
    "3D",
    "5C",
    "6A",
    "6E",
    "7A",
    "9C"
  ],
  "THA388": [
    "1E",
    "1K",
    "4K",
    "6D",
    "7A",
    "7K",
    "8B",
    "8D"
  ],
  "BKP489": [
    "1F",
    "7C",
    "7D",
    "8A",
    "9C",
    "9D",
    "12A"
  ],
  "BTN290": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ],
  "THA391": [
    "4D",
    "5B",
    "5G",
    "7F",
    "7G"
  ],
  "BKP492": [
    "6C",
    "7D",
    "9F",
    "10A",
    "13D",
    "14C"
  ],
  "BTN293": [
    "1D",
    "5B",
    "5C",
    "5E",
    "6D",
    "6E",
    "8C"
  ],
  "THA394": [
    "1E",
    "2F",
    "3F",
    "3G",
    "4D",
    "5J",
    "6F",
    "7B"
  ],
  "BKP495": [
    "2D",
    "3C",
    "4D",
    "5F",
    "6F",
    "8D",
    "11C",
    "13D"
  ],
  "BTN296": [
    "3C",
    "3D",
    "5C",
    "6A",
    "6E",
    "7A",
    "9C"
  ],
  "THA397": [
    "1E",
    "1K",
    "4K",
    "6D",
    "7A",
    "7K",
    "8B",
    "8D"
  ],
  "BKP498": [
    "1F",
    "7C",
    "7D",
    "8A",
    "9C",
    "9D",
    "12A"
  ],
  "BTN299": [
    "3B",
    "5F",
    "6B",
    "7C",
    "8A",
    "8E",
    "9D",
    "10A"
  ],
  "THA400": [
    "1A",
    "1F",
    "3K",
    "4E",
    "6K",
    "7G",
    "8B"
  ],
  "BKP501": [
    "2D",
    "4F",
    "6A",
    "7D",
    "10D",
    "10F",
    "15D"
  ],
  "BTN302": [
    "1F",
    "2A",
    "3D",
    "6C",
    "8D",
    "9C"
  ],
  "THA403": [
    "3K",
    "4K",
    "7G",
    "7K",
    "8G"
  ],
  "BKP504": [
    "3A",
    "3C",
    "9A",
    "12C",
    "13C",
    "14C",
    "15F"
  ],
  "BTN305": [
    "4D",
    "5C",
    "6F",
    "7A",
    "9C",
    "9F"
  ],
  "BKP506": [
    "2A",
    "2E",
    "4A",
    "5A",
    "5D",
    "6A",
    "6D",
    "8A"
  ],
  "BKP507": [
    "2C",
    "2D",
    "4F",
    "9A",
    "12C",
    "13D"
  ],
  "BTN308": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ],
  "THA409": [
    "4D",
    "5B",
    "5G",
    "7F",
    "7G"
  ],
  "BKP510": [
    "2D",
    "4F",
    "6A",
    "7D",
    "10D",
    "10F",
    "15D"
  ],
  "BTN311": [
    "1F",
    "2A",
    "3D",
    "6C",
    "8D",
    "9C"
  ],
  "BKP512": [
    "2B",
    "8A",
    "8F",
    "9C",
    "10C"
  ],
  "BKP513": [
    "3A",
    "3C",
    "9A",
    "12C",
    "13C",
    "14C",
    "15F"
  ],
  "BTN314": [
    "4D",
    "5C",
    "6F",
    "7A",
    "9C",
    "9F"
  ],
  "BKP515": [
    "2A",
    "2E",
    "4A",
    "5A",
    "5D",
    "6A",
    "6D",
    "8A"
  ],
  "BKP516": [
    "2C",
    "2D",
    "4F",
    "9A",
    "12C",
    "13D"
  ],
  "BTN317": [
    "2A",
    "2D",
    "3C",
    "4B",
    "4F",
    "6A",
    "7F",
    "9C"
  ]
};

export const DEFAULT_LOCKED_SEATS = ["1B", "2E", "3A", "3F", "5D", "6B", "6C", "7A", "8F", "9C", "9D"];
export const LOCKED_SEATS_KEY = "botnoi_flight_locked_seats";

export function getLockedSeats(flightNo?: string): string[] {
  if (typeof window === "undefined") {
    return flightNo && DEFAULT_FLIGHT_LOCKED_SEATS[flightNo]
      ? DEFAULT_FLIGHT_LOCKED_SEATS[flightNo]
      : DEFAULT_LOCKED_SEATS;
  }
  try {
    const key = flightNo ? `${LOCKED_SEATS_KEY}_${flightNo}` : LOCKED_SEATS_KEY;
    const data = localStorage.getItem(key);
    if (data) return JSON.parse(data);

    if (flightNo && DEFAULT_FLIGHT_LOCKED_SEATS[flightNo]) {
      return DEFAULT_FLIGHT_LOCKED_SEATS[flightNo];
    }
    return DEFAULT_LOCKED_SEATS;
  } catch {
    return DEFAULT_LOCKED_SEATS;
  }
}

export function saveLockedSeats(seats: string[], flightNo?: string): void {
  if (typeof window === "undefined") return;
  const key = flightNo ? `${LOCKED_SEATS_KEY}_${flightNo}` : LOCKED_SEATS_KEY;
  localStorage.setItem(key, JSON.stringify(seats));
}

export function toggleSeatLock(seatId: string, flightNo?: string): string[] {
  const current = getLockedSeats(flightNo);
  let updated: string[];
  if (current.includes(seatId)) {
    updated = current.filter((s) => s !== seatId);
  } else {
    updated = [...current, seatId];
  }
  saveLockedSeats(updated, flightNo);
  return updated;
}

export function lockSeats(seatIds: string[], flightNo?: string): string[] {
  const current = getLockedSeats(flightNo);
  const updated = Array.from(new Set([...current, ...seatIds]));
  saveLockedSeats(updated, flightNo);
  return updated;
}

export function unlockSeats(seatIds: string[], flightNo?: string): string[] {
  const current = getLockedSeats(flightNo);
  const updated = current.filter((s) => !seatIds.includes(s));
  saveLockedSeats(updated, flightNo);
  return updated;
}

export function unlockAllSeats(flightNo?: string): string[] {
  saveLockedSeats([], flightNo);
  return [];
}

export function resetLockedSeatsToDefault(flightNo?: string): string[] {
  const defaultList = flightNo && DEFAULT_FLIGHT_LOCKED_SEATS[flightNo]
    ? DEFAULT_FLIGHT_LOCKED_SEATS[flightNo]
    : DEFAULT_LOCKED_SEATS;
  saveLockedSeats(defaultList, flightNo);
  return defaultList;
}

export function releaseSeatBooking(
  seatId: string,
  flightNo?: string,
  originCode?: string,
  destCode?: string
): { updatedBookings: Booking[]; updatedLockedSeats: string[]; releasedBooking?: Booking } {
  const allBookings = getBookings();
  let releasedBooking: Booking | undefined;
  const updatedBookings: Booking[] = [];

  for (const b of allBookings) {
    if (!b.seat) {
      updatedBookings.push(b);
      continue;
    }
    const seats = b.seat.split(",").map((s) => s.trim());
    const bOrig = getAirportCode(b.from);
    const bDest = getAirportCode(b.to);

    const matchesRoute = (!originCode || bOrig === originCode) && (!destCode || bDest === destCode);
    const matchesFlight =
      !flightNo ||
      b.outboundFlightNo === flightNo ||
      b.inboundFlightNo === flightNo ||
      b.legs?.some((l) => l.flightNo === flightNo) ||
      !b.outboundFlightNo;

    if (seats.includes(seatId) && matchesFlight && (matchesRoute || !originCode)) {
      releasedBooking = b;
      const remainingSeats = seats.filter((s) => s !== seatId);
      if (remainingSeats.length > 0) {
        updatedBookings.push({
          ...b,
          seat: remainingSeats.join(", "),
          passengers: Math.max(1, remainingSeats.length),
        });
      }
    } else {
      updatedBookings.push(b);
    }
  }

  if (typeof window !== "undefined") {
    localStorage.setItem(KEY, JSON.stringify(updatedBookings));
  }

  // Also remove from lockedSeats if present
  const currentLocked = getLockedSeats(flightNo);
  const updatedLocked = currentLocked.filter((s) => s !== seatId);
  saveLockedSeats(updatedLocked, flightNo);

  return {
    updatedBookings,
    updatedLockedSeats: updatedLocked,
    releasedBooking,
  };
}

export function forceLockBookedSeat(seatId: string, flightNo?: string, originCode?: string, destCode?: string): string[] {
  releaseSeatBooking(seatId, flightNo, originCode, destCode);
  const currentLocked = getLockedSeats(flightNo);
  const updatedLocked = Array.from(new Set([...currentLocked, seatId]));
  saveLockedSeats(updatedLocked, flightNo);
  return updatedLocked;
}

export type CabinType = "turboprop" | "narrowbody" | "widebody";

export function getAircraftCabinType(model?: string, type?: string): CabinType {
  const m = (model || "").toLowerCase();
  const t = (type || "").toLowerCase();
  if (m.includes("atr") || t.includes("turboprop") || t.includes("regional")) {
    return "turboprop";
  }
  if (m.includes("777") || m.includes("787") || m.includes("350") || m.includes("wide") || t.includes("wide")) {
    return "widebody";
  }
  return "narrowbody";
}

